### ISSUE TITLE
JISON compiler

### ISSUE THREAD

**Issue by khelle** [AdamBrodzinski/RedScript#8]
Hello,
some time ago I have written a compiler for RedScript in JISON. It was about two years ago, but I am not familiar if there were any ground breaking changes in the specification. I am willing to collaborate on the project to improve it further if there is any interest from the author and/or people using it.

https://github.com/khelle/redscript-compiler

**Comment by AdamBrodzinski** [comment]
@khelle This is amazing! Many thanks!! 🍻 

I'm moving this weekend so I don't have a ton of time but i'll check this out and create a list of things that have changed since the original 1.0. In general I wanted to move away from OO because JS does it so poorly (and ES6 does a decent job of emulating it). However I think 90% of the code is the same 😄

**Comment by AdamBrodzinski** [comment]
@khelle I was checking out the compiler today and ran into an issue when a string is used:

```
redscript-compiler|master ⇒ node redscript.js foo.rds > foo.js

/Users/adam/Projects/redscript-compiler/redscript.js:430
        throw new _parseError(str, hash);
        ^
Error: Parse error on line 1:
puts "Hello World"
-----^
Expecting 'PRIVATE', 'END', 'IDENTIFIER', '=', ':', 'FUNCTION', 'CONST', 'DELETE', 'IF', 'ELSE', 'WHILE', 'UNTIL', 'FOR', 'CONTINUE', 'BREAK', 'RETURN', 'WITH', 'SWITCH', 'WHEN', 'DEFAULT', 'THROW', 'TRY', 'FINALLY', 'CATCH', 'DEBUGGER', 'CLASS', 'DEF', 'OBJECT', 'DEFINE', 'EXPORT', 'EOF', got 'STRING'
```

using this as the rds file:

```
puts "Hello World"
```

Is there something different I need to do?

Cheers!
Adam

**Comment by khelle** [comment]
Sorry, for the delay. I realized I have uploaded unfinished version of compiler `0.7.8`. I have now updated it with the newest verstion of `0.9.0` that works - almost - correctly. Additionally, I have attached set of examples. Unfortunately, the current version does not support calling methods without braces, so it needs to be called as `puts('Hello World')`.  I would be able to change this behaviour after you deliver me the newer and complete version of Redscript up-to-date syntax.

**Comment by AdamBrodzinski** [comment]
@khelle thanks for looking into this! I'll try out this tonight or tomorrow. Is there a certain way to write out the syntax that would be most helpful? Would following a more simple version of the JS spec pdf you have in your repo be helpful?

Also I really wouldn't mind if optional parens were not included as i've had readability issues with them in the past (also Elixir is suggesting against omitting them also for ambiguity reasons)

**Comment by AdamBrodzinski** [comment]
Here's a new spec i'm working on. Please let me know if I should add more information or in a different style 👍 

https://github.com/AdamBrodzinski/RedScript/blob/master/spec.md

**Comment by khelle** [comment]
Yes, I am using only JISON for this. It is really awesome tool for creating different kind of parsers and interpreters. Let me know when the spec is finished.

**Comment by fazibear** [comment]
Woohaa, it is something going on here 👍 What about elixir like macros ? Is it possible with jison ?

**Comment by AdamBrodzinski** [comment]
@khelle great, trying to finish it up this week!

@fazibear yeah thanks to @khelle I think we'll have a really usable language here 😬  @fazibear  Can you checkout the spec here to see what you think so far? I'm not sure about macro support, I know there are some experimental JS libs. I think module function pattern matching is higher up on my list as it can be used more day to day.

https://github.com/AdamBrodzinski/RedScript/blob/master/spec.md

One thing I would love to do later on is prevent the `foo.bar.baz`, `bar is undefined`. Currently you can use lodash with `_.get(foo, 'bar.baz')` to prevent an undefined nested value but i'm not sure how hard this is to  transform on the compiler level.

**Comment by fazibear** [comment]
@AdamBrodzinski This is my thoughts about redscript in todays javascript ecosystem.

1) We should generate ES6 instead of browsers javascript. We can trarget node and also browsers. Babel will take care of features that are exist or not in node/browser environment. Moreover we will be able to just plug redscript into build chain and take advantages of both. 

2) Lanaguage spec should be much closer to ES6 syntax but without parentheses, comas and stuff like that. It would be the best and more successful if redscript be a superset of ES6. This is why babel or typescript is so popular. Javascript is also a valid typescript (or ES6). For example, in redscript commas and parentheses are optional, so you can change extension from js to rs, and if you like remove all commas, parentheses, replace {} blocks with do...end etc... I think that will fit the best todays javascript ecosystem. Redscript features will remove JS noise and make code more readable, but with compatibility. 

3) We should not try to simulate Ruby or Elixir runtime. There are Opal and ElixirScript, but bot have disadvantages. In Opal you have to make wrappers for all objects. ElixirScript compiler generates ES6, and you have to use both. What we need is something that can be plugged into your build system and make your code cleaner. Every JS app have some build system now days.

4) What about features ? All ES6 features in easy to read form (transformed a little). ES6 has a classes, thats good, generator ? OK. But also things that JS lack. String concatenation, pipe operator, or even pattern matching witch is pretty be easy, tool to create ruby like dsl. I think just removing parentheses and commas will be a big advantages. 

5) Target. First think is to write for example react/redux application without JS noise, and with features described it is possible. Also new framework that will be written in redscript. I wrote simple web framework in Opal (ruby). Application code is very easy to read, one disadvantage is wrappers for existing js libraries, and runtime of course. Tried same think in elixirscript, but failed because compilation is not easy.

Feedback is appreciate.

**Comment by AdamBrodzinski** [comment]
Thanks for the feedback @fazibear 

I think we agree on a lot.

1.  Yeah I think generating ES6 makes the most sense and then a build step can compile it down further if needed. 

2. I think we differ a bit here, I really want to make using functional constructs easier so having a bit more than removing parens and semicolons. I think coffeescript went with the 'type less' route and a lot of people found it to not be worth it (the extra trouble vs es6). One of the things i'd like to do is have rs files be free of object/array mutation (though js could still do that of course).

3. I agree it shouldn't just replicate Elixir exactly... ElixirScript is doing a great job of that! I'd like to bring over the 'functional mentality', immutability, good tooling (maybe some mix like features in the CLI), and a decent standard lib (perhaps more built in lodash and less elixir std lib)

4,5. agreed 🍻 

Thanks!
